
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'HT\xd99E\xed^\x1ac\xa6\x8e\xaf\xcb&g\xb4'
    
_lr_action_items = {'LOAD':([0,1,],[1,1,]),'PATH':([0,1,],[2,2,]),'SCOL':([2,4,5,],[-2,5,-1,]),'$end':([2,3,5,],[-2,0,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,1,],[3,4,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> LOAD expression SCOL','expression',3,'p_expressoin_load','/Users/pb/code/sau/lib/sau/sau_parser.py',258),
  ('expression -> PATH','expression',1,'p_expression_path','/Users/pb/code/sau/lib/sau/sau_parser.py',262),
]
